server:
  port: 8083

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yg_user_transactions
    username: root
    password:
  jpa:
    hibernate.ddl-auto: create
    generate-ddl: true
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080
  rabbitmq:
    host: localhost
    port: 15672
    username: guest
    password: guest